version: '3.8'

services:
  postgres:
    image: postgres:16.0-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: prediction
      POSTGRES_PASSWORD: prediction
      POSTGRES_DB: prediction
    restart: always


  informationpanelmed:
    build:
      context: .
    ports:
      - "8010:8010"
    depends_on:
      - postgres
    environment:
      DEBUG: "False"
      DB_NAME: "prediction"
      DB_USER: "prediction"
      DB_PASSWORD: "prediction"
      DB_HOST: "postgres"
      DB_PORT: 5432
    restart: always
