# Generated by Django 5.0.1 on 2024-01-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredPatients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdivision', models.CharField(max_length=50)),
                ('speciality', models.CharField(max_length=255)),
                ('slots_today', models.IntegerField()),
                ('free_slots_today', models.IntegerField()),
                ('slots_14_days', models.IntegerField()),
                ('free_slots_14_days', models.IntegerField()),
            ],
        ),
    ]
