# Generated by Django 5.0.1 on 2024-01-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peopledash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredpatients',
            name='report_datetime',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
